###########################################################################################################
# 1.0 Spring Configuartions                                                                               #
###########################################################################################################
spring:
  application:
    name: spring-jpa-pagination-sorting-filtering-demo

  cache:
    ehcache:
      config: classpath:ehcache.xml
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true



    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

debug: true
   
webcrawler.default:
  depth: 2
  breadth: -1
  individual.page.download.timeout.in.millis: 5000     


#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root123
  password: root123
  url: jdbc:mysql://localhost:3306/crawler
  # The SQL dialect makes Hibernate generate better SQL for the chosen database

  # Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa:
  hibernate.ddl-auto: update
  generate-ddl: true
  show-sql: true


